class CityData {
  static const List<Map<String, String>> turkishCities = [
    {'name': 'Adana', 'code': '01'},
    {'name': 'Adiyaman', 'code': '02'},
    {'name': 'Afyonkarahisar', 'code': '03'},
    {'name': 'Agri', 'code': '04'},
    {'name': 'Aksaray', 'code': '68'},
    {'name': 'Amasya', 'code': '05'},
    {'name': 'Ankara', 'code': '06'},
    {'name': 'Antalya', 'code': '07'},
    {'name': 'Ardahan', 'code': '75'},
    {'name': 'Artvin', 'code': '08'},
    {'name': 'Aydin', 'code': '09'},
    {'name': 'Balikesir', 'code': '10'},
    {'name': 'Bartin', 'code': '74'},
    {'name': 'Batman', 'code': '72'},
    {'name': 'Bayburt', 'code': '69'},
    {'name': 'Bilecik', 'code': '11'},
    {'name': 'Bingol', 'code': '12'},
    {'name': 'Bitlis', 'code': '13'},
    {'name': 'Bolu', 'code': '14'},
    {'name': 'Burdur', 'code': '15'},
    {'name': 'Bursa', 'code': '16'},
    {'name': 'Canakkale', 'code': '17'},
    {'name': 'Cankiri', 'code': '18'},
    {'name': 'Corum', 'code': '19'},
    {'name': 'Denizli', 'code': '20'},
    {'name': 'Diyarbakir', 'code': '21'},
    {'name': 'Duzce', 'code': '81'},
    {'name': 'Edirne', 'code': '22'},
    {'name': 'Elazig', 'code': '23'},
    {'name': 'Erzincan', 'code': '24'},
    {'name': 'Erzurum', 'code': '25'},
    {'name': 'Eskisehir', 'code': '26'},
    {'name': 'Gaziantep', 'code': '27'},
    {'name': 'Giresun', 'code': '28'},
    {'name': 'Gumushane', 'code': '29'},
    {'name': 'Hakkari', 'code': '30'},
    {'name': 'Hatay', 'code': '31'},
    {'name': 'Isparta', 'code': '32'},
    {'name': 'Istanbul', 'code': '34'},
    {'name': 'Izmir', 'code': '35'},
    {'name': 'Kahramanmaras', 'code': '46'},
    {'name': 'Karabuk', 'code': '78'},
    {'name': 'Karaman', 'code': '70'},
    {'name': 'Kars', 'code': '36'},
    {'name': 'Kastamonu', 'code': '37'},
    {'name': 'Kayseri', 'code': '38'},
    {'name': 'Kirikkale', 'code': '71'},
    {'name': 'Kirklareli', 'code': '39'},
    {'name': 'Kirsehir', 'code': '40'},
    {'name': 'Kilis', 'code': '79'},
    {'name': 'Kocaeli', 'code': '41'},
    {'name': 'Konya', 'code': '42'},
    {'name': 'Kutahya', 'code': '43'},
    {'name': 'Malatya', 'code': '44'},
    {'name': 'Manisa', 'code': '45'},
    {'name': 'Mardin', 'code': '47'},
    {'name': 'Mersin', 'code': '33'},
    {'name': 'Mugla', 'code': '48'},
    {'name': 'Mus', 'code': '49'},
    {'name': 'Nevsehir', 'code': '50'},
    {'name': 'Nigde', 'code': '51'},
    {'name': 'Ordu', 'code': '52'},
    {'name': 'Osmaniye', 'code': '80'},
    {'name': 'Rize', 'code': '53'},
    {'name': 'Sakarya', 'code': '54'},
    {'name': 'Samsun', 'code': '55'},
    {'name': 'Siirt', 'code': '56'},
    {'name': 'Sinop', 'code': '57'},
    {'name': 'Sivas', 'code': '58'},
    {'name': 'Sanliurfa', 'code': '63'},
    {'name': 'Sirnak', 'code': '73'},
    {'name': 'Tekirdag', 'code': '59'},
    {'name': 'Tokat', 'code': '60'},
    {'name': 'Trabzon', 'code': '61'},
    {'name': 'Tunceli', 'code': '62'},
    {'name': 'Usak', 'code': '64'},
    {'name': 'Van', 'code': '65'},
    {'name': 'Yalova', 'code': '77'},
    {'name': 'Yozgat', 'code': '66'},
    {'name': 'Zonguldak', 'code': '67'},
  ];

  static const Map<String, List<String>> districtData = {
    'Adana': ['Aladag', 'Ceyhan', 'Çukurova', 'Feke', 'Imamoglu', 'Karaisal', 'Karatas', 'Kozan', 'Pozanti', 'Saimbeyli', 'Seyhan', 'Tufanbeyli', 'Yumurtalik', 'Yüreðir'],
    'Adiyaman': ['Besni', 'Çelikhan', 'Gerger', 'Gölbaþi', 'Kahta', 'Samsat', 'Sincik', 'Tut'],
    'Afyonkarahisar': ['Baþmakç', 'Bayat', 'Bolvadin', 'Çay', 'Çobanlar', 'Dazkiri', 'Dinar', 'Emirdag', 'Evciler', 'Hocalar', 'Ihsaniye', 'Ihsaniye', 'Iþýklar', 'Kizilören', 'Sandikli', 'Sinanpaþa', 'Sultandaði', 'Þuhut'],
    'Agri': ['Diyadin', 'Dogubeyazit', 'Eleþkirt', 'Iðdir', 'Karayazý', 'Patnos', 'Taþlýçay', 'Tutak'],
    'Aksaray': ['Aksaray', 'Eskil', 'Gülaðaç', 'Güzelyurt', 'Ortaköy', 'Sariyahþi'],
    'Amasya': ['Amasya', 'Göynücek', 'Gümüþhacýköy', 'Hamamözü', 'Merzifon', 'Suluova', 'Taþova'],
    'Ankara': ['Altýndað', 'Ayaþ', 'Bala', 'Beypazarý', 'Çamlýdere', 'Çankaya', 'Çubuk', 'Elmadað', 'Güdül', 'Haymana', 'Kalecik', 'Kazan', 'Keskin', 'Kýzýlcahamam', 'Mamak', 'Nallýhan', 'Polatlý', 'Pursaklar', 'Sincan', 'Þereflikoçhisar', 'Yenimahalle'],
    'Antalya': ['Akseki', 'Aksu', 'Alanya', 'Demre', 'Elmalý', 'Finike', 'Gazipaþa', 'Gündoðmuþ', 'Isparta', 'Kaþ', 'Kemer', 'Kepez', 'Konyaaltý', 'Kumluca', 'Manavgat', 'Muratpaþa', 'Serik'],
    'Ardahan': ['Ardahan', 'Çýldýr', 'Damal', 'Göle', 'Hanak', 'Posof'],
    'Artvin': ['Ardanuç', 'Arhavi', 'Borçka', 'Hopa', 'Kemalpaþa', 'Murgul', 'Þavþat', 'Yusufeli'],
    'Aydin': ['Bozdogan', 'Buharkent', 'Çine', 'Didim', 'Efeler', 'Germencik', 'Incirliova', 'Karacasu', 'Karpuzlu', 'Koçarlý', 'Köþk', 'Kuyucak', 'Kþýlýcahisar', 'Nazilli', 'Söke', 'Sultanhisar', 'Yenipazar', 'Yeniköy'],
    'Balikesir': ['Altýeylül', 'Ayvalýk', 'Balya', 'Bandýrma', 'Bigadiç', 'Burhaniye', 'Dursunbey', 'Edremit', 'Erdek', 'Gömeç', 'Gönen', 'Havran', 'Ivrindi', 'Karesi', 'Kepsut', 'Manyas', 'Marmara', 'Savaþtepe', 'Sýndýrgý', 'Susurluk'],
    'Bartin': ['Amasra', 'Bartin', 'Kurucaþile', 'Ulus'],
    'Batman': ['Batman', 'Beþiri', 'Gercüþ', 'Hasankeyf', 'Kozluk', 'Sason'],
    'Bayburt': ['Aydýntepe', 'Bayburt', 'Demirözü'],
    'Bilecik': ['Bilecik', 'Bozüyük', 'Gölpazarý', 'Ýnhisar', 'Osmaneli', 'Pazaryeri', 'Söðüt', 'Yenipazar'],
    'Bingol': ['Adaklý', 'Bingöl', 'Genç', 'Karliova', 'Kiði', 'Solhan', 'Yayladere', 'Yedisu'],
    'Bitlis': ['Adilcevaz', 'Ahlat', 'Bitlis', 'Güroymak', 'Hizan', 'Mutki', 'Tatvan'],
    'Bolu': ['Bolu', 'Dörtdivan', 'Gerede', 'Göynük', 'Kýbrýscýk', 'Mengen', 'Mudurnu', 'Seben', 'Yeniçaða'],
    'Burdur': ['Aðlasun', 'Bucak', 'Burdur', 'Çavdýr', 'Çeltikçi', 'Gölhisar', 'Karamanlý', 'Kemer', 'Tefenni', 'Yeþilova'],
    'Bursa': ['Büyükorhan', 'Gemlik', 'Gürsu', 'Harmancýk', 'Ýnegöl', 'Karacabey', 'Keles', 'Kestel', 'Mudanya', 'Mustafakemalpaþa', 'Nilüfer', 'Orhaneli', 'Orhangazi', 'Osmangazi', 'Yeniþehir', 'Yýldýrým'],
    'Canakkale': ['Ayvacýk', 'Bayramiç', 'Biga', 'Bozcaada', 'Çan', 'Çanakkale', 'Eceabat', 'Ezine', 'Gelibolu', 'Gökçeada', 'Lapseki', 'Yenice'],
    'Cankiri': ['Atkaracalar', 'Bayramören', 'Çerkeþ', 'Çankýrý', 'Eldivan', 'Ilgaz', 'Kýzýlýrmak', 'Korgun', 'Kurþunlu', 'Orta', 'Þabanözü', 'Yapraklý'],
    'Corum': ['Alaca', 'Bayat', 'Boðazkale', 'Çorum', 'Dodurga', 'Ismaylý', 'Kargý', 'Laçin', 'Mecitözü', 'Oðuzlar', 'Osmancýk', 'Sungurlu', 'Uðurludað'],
    'Denizli': ['Acýpayam', 'Babadað', 'Baklan', 'Bekilli', 'Beyaðaç', 'Buldan', 'Çal', 'Çameli', 'Çardak', 'Çivril', 'Güney', 'Honaz', 'Kale', 'Merkezefendi', 'Pamukkale', 'Sarayköy', 'Serinhisar', 'Tavas'],
    'Diyarbakir': ['Baðlar', 'Bismil', 'Çermik', 'Çýn', 'Dicle', 'Eðil', 'Ergani', 'Hani', 'Hazro', 'Kayapýnar', 'Kocaköy', 'Kulp', 'Lice', 'Silvan', 'Sur', 'Yeniþehir'],
    'Duzce': ['Akçakoca', 'Cumayeri', 'Çilimli', 'Gölyaka', 'Gümüþova', 'Kaynaþlý', 'Yýðýlca'],
    'Edirne': ['Edirne', 'Enez', 'Havsa', 'Ýpsala', 'Keþan', 'Lalapaþa', 'Meriç', 'Süloðlu', 'Uzunköprü'],
    'Elazig': ['Aðýn', 'Alacakaya', 'Arýcakkale', 'Baskil', 'Elazýð', 'Karakoçan', 'Keban', 'Kovancýlar', 'Maden', 'Palu', 'Sivrice'],
    'Erzincan': ['Çayýrlý', 'Erzincan', 'Ýliç', 'Kemah', 'Kemaliye', 'Otlukbeli', 'Refahiye', 'Tercan', 'Üzümlü'],
    'Erzurum': ['Aþkale', 'Aziziye', 'Çat', 'Hýsnýkazým', 'Horasan', 'Ýspir', 'Karaçoban', 'Karayazý', 'Köprüköy', 'Narman', 'Nazar', 'Oltu', 'Olur', 'Pazaryolu', 'Þenkaya', 'Tekman', 'Tortum', 'Uzundere'],
    'Eskisehir': ['Alpu', 'Beylikova', 'Çifteler', 'Günyüzü', 'Han', 'Inönü', 'Mahmudiye', 'Mihalgazi', 'Mihalýççýk', 'Odunpazarý', 'Sarýcakaya', 'Seyitgazi', 'Sivrihisar', 'Tepebaþý'],
    'Gaziantep': ['Araban', 'Þahinbey', 'Þehitkamil', 'Þehitkamil', 'Karkamýþ', 'Nizip', 'Nurdaðý', 'Oðuzeli', 'Yavuzeli'],
    'Giresun': ['Alucra', 'Bulancak', 'Çamoluk', 'Çanakçi', 'Dereli', 'Doðankent', 'Eynesil', 'Giresun', 'Görele', 'Güce', 'Keþap', 'Piraziz', 'Þebinkarahisar', 'Tirebolu', 'Yaðlýdere'],
    'Gumushane': ['Gümüþhane', 'Kelkit', 'Köse', 'Kürtün', 'Þiran', 'Torul'],
    'Hakkari': ['Çukurca', 'Hakkari', 'Merkez', 'Þemdinli', 'Yüksekova'],
    'Hatay': ['Altýnözu', 'Arsuz', 'Belen', 'Defne', 'Dörtyol', 'Erzin', 'Hassa', 'Ýskenderun', 'Kirikhan', 'Kumlu', 'Payas', 'Reyhanlý', 'Samandað', 'Yayladaðý'],
    'Isparta': ['Atabey', 'Eðirdir', 'Gelendost', 'Gönen', 'Isparta', 'Keçiborlu', 'Senirkent', 'Sütçüler', 'Þarkikaraaðaç', 'Uluborlu', 'Yeniþarbademli', 'Yalvaç'],
    'Istanbul': ['Adalar', 'Arnavutköy', 'Ataþehir', 'Avcýlar', 'Baðcýlar', 'Bahçelievler', 'Bakýrköy', 'Baþakþehir', 'Bayrampaþa', 'Beþiktaþ', 'Beykoz', 'Beylikdüzü', 'Beyoðlu', 'Büyükçekmece', 'Çatalca', 'Çekmeköy', 'Esenler', 'Esenyurt', 'Eyüp', 'Fatih', 'Gaziosmanpaþa', 'Güngören', 'Kadýköy', 'Kaðýthane', 'Kartal', 'Küçükçekmece', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sariyer', 'Sultanbeyli', 'Þile', 'Þiþli', 'Tuzla', 'Ümraniye', 'Üsküdar', 'Zeytinburnu'],
    'Izmir': ['Aliaða', 'Balçova', 'Bayýndýr', 'Bayraklý', 'Bergama', 'Beydað', 'Bornova', 'Buca', 'Çeþme', 'Çiðli', 'Dikili', 'Foça', 'Gaziemir', 'Güzelbahçe', 'Karabaðlar', 'Karaburun', 'Karþýyaka', 'Kemalpaþa', 'Kýnalký', 'Konak', 'Menderes', 'Menemen', 'Narlýdere', 'Ödemiþ', 'Seferihisar', 'Selçuk', 'Tire', 'Torbalý', 'Urla'],
    'Kahramanmaras': ['Afþin', 'Andýrýn', 'Çaðlayancerit', 'Ekinözü', 'Elbistan', 'Göksun', 'Kahramanmaraþ', 'Nurhak', 'Pazarcýk', 'Türkoðlu'],
    'Karabuk': ['Eflani', 'Eskipazar', 'Karabük', 'Ovacýk', 'Safranbolu', 'Yenice'],
    'Karaman': ['Ayrancý', 'Baþyayla', 'Ermenek', 'Karaman', 'Kazýmkarabekir', 'Sarýveliler'],
    'Kars': ['Akyaka', 'Arpaçay', 'Digor', 'Kaðýzman', 'Kars', 'Selim', 'Susuz'],
    'Kastamonu': ['Aðlý', 'Araç', 'Azdavay', 'Bozkurt', 'Çatalzeytin', 'Cide', 'Daday', 'Devrekani', 'Doðanyurt', 'Hanönü', 'Ýhsangazi', 'Ýnebolu', 'Kastamonu', 'Küre', 'Pehlivanköy', 'Seydiler', 'Þenpazar', 'Taþköprü', 'Tosya'],
    'Kayseri': ['Bünyan', 'Develi', 'Felahiye', 'Hacýlar', 'Incesu', 'Kocasinan', 'Melikgazi', 'Özvatan', 'Pýnarbaþý', 'Sarýoðlan', 'Sarýz', 'Talas', 'Tomarza', 'Yahyalý', 'Yeþilhisar'],
    'Kirikkale': ['Bahþili', 'Balýseyh', 'Çelebi', 'Delice', 'Karakeçili', 'Keskin', 'Kýrýkkale', 'Sulakyurt', 'Yahþihan'],
    'Kirklareli': ['Babaeski', 'Demirköy', 'Kýrklareli', 'Kofçaz', 'Lüleburgaz', 'Pehlivanköy', 'Pýnarhisar', 'Vize'],
    'Kirsehir': ['Akçakent', 'Akpýnar', 'Boztepe', 'Çiçekdaðý', 'Kaman', 'Kýrþehir', 'Mucur', 'Özbað'],
    'Kilis': ['Elbeyli', 'Kilis', 'Musabeyli', 'Polateli'],
    'Kocaeli': ['Baþiskele', 'Çaycova', 'Darýca', 'Derince', 'Dilovasý', 'Gebze', 'Gölcük', 'Kandýra', 'Karamürsel', 'Kartepe', 'Körfez'],
    'Konya': ['Ahýrlý', 'Akören', 'Akþehir', 'Altnýekin', 'Beyþehir', 'Bozkýr', 'Çeltik', 'Cihanbeyli', 'Çumra', 'Derbent', 'Derebucak', 'Doganhisar', 'Doganlar', 'Emirgazi', 'Ereðli', 'Güneysýnýr', 'Hadim', 'Halkapýnar', 'Hüyük', 'Ilgýn', 'Kadýnhaný', 'Karapýnaryayla', 'Karatay', 'Kulu', 'Kumluca', 'Meram', 'Sarayönü', 'Selçuklu', 'Seydiþehir', 'Taþkent', 'Tuzlukçu', 'Yalýhüyük', 'Yunak', 'Yeniðöl'],
    'Kutahya': ['Altýntaþ', 'Aslanapa', 'Çavdarhisar', 'Domaniç', 'Dumlupýnar', 'Emet', 'Gediz', 'Hisarcýk', 'Ýlisu', 'Kütahya', 'Pazarlar', 'Þaphane', 'Simav', 'Tavþanlý'],
    'Malatya': ['Akçadað', 'Arapgir', 'Arguvan', 'Battalgazi', 'Darende', 'Doðanþehir', 'Doðanyol', 'Hekimhan', 'Kale', 'Kuluncak', 'Malatya', 'Pötürge', 'Yazýhan', 'Yeþilyurt'],
    'Manisa': ['Ahmetli', 'Akhisar', 'Alaþehir', 'Demirci', 'Gölmarmara', 'Gördes', 'Kýrkaðaç', 'Köprübaþý', 'Kula', 'Manisa', 'Sarýgöl', 'Saruhanlý', 'Selendi', 'Turgutlu', 'Þehzadeler'],
    'Mardin': ['Dargeçit', 'Derik', 'Kýzýltepe', 'Mazýdaðý', 'Mardin', 'Midyat', 'Nusaybin', 'Ömerli', 'Savur', 'Yeþilli'],
    'Mersin': ['Anamur', 'Aydýncýk', 'Bozyazý', 'Çamlýyayla', 'Erdemli', 'Gülnar', 'Mut', 'Silifke', 'Tarsus'],
    'Mugla': ['Bodrum', 'Dalaman', 'Datça', 'Fethiye', 'Kavaklýdere', 'Köyceðiz', 'Marmaris', 'Menteþe', 'Milas', 'Ortaca', 'Ula', 'Yataðan'],
    'Mus': ['Bulanýk', 'Hasköy', 'Korkut', 'Malazgirt', 'Mus', 'Varto'],
    'Nevsehir': ['Acýgöl', 'Avanos', 'Derinkuyu', 'Gülþehir', 'Hacýbektaþ', 'Kozaklý', 'Nevþehir', 'Ürgüp'],
    'Nigde': ['Bor', 'Çamardý', 'Çiftlik', 'Nigde', 'Ulukýþla'],
    'Ordu': ['Akkuþ', 'Altýnordu', 'Çamaþ', 'Çatalpýnar', 'Fatsa', 'Gölköy', 'Gülyalý', 'Gürgentepe', 'Ýkizce', 'Kabadüz', 'Kabataþ', 'Korgan', 'Kumru', 'Mesudiye', 'Perþembe', 'Ulubey', 'Ünye'],
    'Osmaniye': ['Bahçe', 'Düziçi', 'Hasanbeyli', 'Kadirli', 'Osmaniye', 'Sumbas', 'Toprakkale'],
    'Rize': ['Ardeþen', 'Çamlýþemþin', 'Derepazarý', 'Fýndýklý', 'Güneysu', 'Hemþin', 'Ýkizdere', 'Kalkandere', 'Pazar', 'Arakli'],
    'Sakarya': ['Adapazarý', 'Akyazý', 'Arifiye', 'Erenler', 'Ferizli', 'Geyve', 'Hendek', 'Karapürçek', 'Karasu', 'Kaynarca', 'Kocaali', 'Pamukova', 'Sapanca', 'Serdivan', 'Söðütlü', 'Taraklý'],
    'Samsun': ['Alaçam', 'Asarcýk', 'Atakum', 'Ayvacýk', 'Bafra', 'Çarþamba', 'Havza', 'Ýlkadým', 'Kavak', 'Ladik', 'Ondokuzmayýs', 'Salýpazarý', 'Tekkeköy', 'Terme', 'Vezirköprü', 'Yakakent'],
    'Siirt': ['Baykan', 'Eruh', 'Kurtalan', 'Perwar', 'Siirt', 'Tillo'],
    'Sinop': ['Ayancýk', 'Boyabat', 'Dikmen', 'Duraðan', 'Erfelek', 'Gerze', 'Saraydüzü', 'Sinop', 'Türkeli', 'Yenikent'],
    'Sivas': ['Akýncýlar', 'Alac', 'Altýnyayla', 'Divriði', 'DoðanÞar', 'Gemerek', 'Gölova', 'Gürün', 'Hafik', 'Ýmranlý', 'Kangal', 'Koyulhisar', 'Kuruçay', 'Þarkýþla', 'Sivas', 'Suþehri', 'Þebinkarahisar', 'Yýldýzeli', 'Zara'],
    'Sanliurfa': ['Akçakale', 'Birecik', 'Bozova', 'Ceylanpýnar', 'Eyyübiye', 'Halfeti', 'Haliliye', 'Hilvan', 'Karaköprü', 'Siverek', 'Suruç', 'Viranþehir'],
    'Sirnak': ['Beytüsþebap', 'Cizre', 'Güçlükonak', 'Ýdil', 'Silopi', 'Uludere'],
    'Tekirdag': ['Çorlu', 'Ergene', 'Hayrabolu', 'Kapaklý', 'Malkara', 'Marmara Ereðlisi', 'Muratlý', 'Saray', 'Süleymanpaþa', 'Þarköy'],
    'Tokat': ['Artova', 'Baþçiftlik', 'Erbaa', 'Niksar', 'Pazar', 'Reþadiye', 'Sulusaray', 'Tokat', 'Turhal', 'Yeþilyurt', 'Zile'],
    'Trabzon': ['Akçaabat', 'Araklý', 'Arsin', 'Beþikdüzü', 'Çarþýbaþý', 'Çaykara', 'Dernekpazarý', 'Düzköy', 'Hayrat', 'Köprübaþý', 'Maçka', 'Of', 'Sürmene', 'Tonya', 'Vakfýkebir', 'Yomra'],
    'Tunceli': ['Çemiþgezek', 'Hozat', 'Mazgirt', 'Nazimiye', 'Ovacýk', 'Pertek', 'Pülümür', 'Tunceli'],
    'Usak': ['Banaz', 'Eþme', 'Karahallý', 'Sivaslý', 'Ulubey', 'Usak'],
    'Van': ['Baþkale', 'Çatak', 'Edremit', 'Erciþ', 'Gevaþ', 'Gürpýnar', 'Ýpekyolu', 'Muradiye', 'Özalp', 'Saray', 'Tuþba'],
    'Yalova': ['Altýnova', 'Armutlu', 'Çýnarcýk', 'Termal', 'Yalova'],
    'Yozgat': ['Akdaðmadeni', 'Aydýncýk', 'Boðazlayan', 'Çandýr', 'Çekerek', 'KadýÞehir', 'Saraykent', 'Sarýkaya', 'Sorgun', 'Þefaatli', 'Yenifakýlý', 'Yerköy', 'Yozgat'],
    'Zonguldak': ['Alapli', 'Çaycuma', 'Devrek', 'Ereðli', 'Gökçebey', 'Kilimli', 'Kozlu', 'Zonguldak'],
  };

  static List<String> getDistricts(String cityName) {
    return districtData[cityName] ?? [];
  }

  static List<Map<String, String>> searchCities(String query) {
    if (query.isEmpty) return turkishCities;
    
    return turkishCities.where((city) {
      final name = city['name']!.toLowerCase();
      final code = city['code']!.toLowerCase();
      final searchQuery = query.toLowerCase();
      return name.contains(searchQuery) || code.contains(searchQuery);
    }).toList();
  }
}
